# This file could be used for testing the API with Visual Studio Code

## Log in
POST http://localhost:3001/api/sessions HTTP/1.1
content-type: application/json

{
  "username": "User",
  "isRestaurateur": "0"
}
###

## Checking if user is still logged-in.
GET http://localhost:3001/api/sessions/current HTTP/1.1
###

## Execute Log Out.
DELETE http://localhost:3001/api/sessions/current HTTP/1.1
###

## Get the info of the user with that username
GET http://localhost:3001/api/users/User HTTP/1.1
###

## Update the info of the user with that username
POST http://localhost:3001/api/users/User HTTP/1.1
content-type: application/json

{
  "username": "User",
  "position": "posssss",
  "isRestaurateur": "0"
}
###

## Get All The restaurants
GET http://localhost:3001/api/restaurants HTTP/1.1
###

## Get a restaurant from his id
GET http://localhost:3001/api/restaurants/1 HTTP/1.1
###

## Get the inserted restaurants
GET http://localhost:3001/api/insertedrestaurants/ HTTP/1.1
###

## Get the available categories and allergens
GET http://localhost:3001/api/filterinfos/ HTTP/1.1
###

## Get complete infos of an ingredient 
GET http://localhost:3001/api/ingredients/3 HTTP/1.1
###

## Get a given dish
GET http://localhost:3001/api/dishes/1 HTTP/1.1
###

## Insert a new Restaurant
POST http://localhost:3001/api/restaurants HTTP/1.1
content-type: application/json

{
  "isNewInserted": 0,
  "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAEnQAABJ0Ad5mH3gAAABrSURBVBhXHcaxCoJQFIDh39MVLBpCtLmtoAafNHqThp7HwUUEE0yKuB6vp3D44Iuut9KK/Z1L/iBNKiRSZGUB+WOGEBw6rRGCLHn7jO5zoBnOuFG3tMMJUwcGX5/i/Lij7gueryM2x0y64Qemmyv/QTYLjwAAAABJRU5ErkJggg==",
  "name": "Sorbillo",
  "location": "Via Bruno Buozzi, 3, 10121 Torino TO",
  "phone": "011 1923 4672",
  "website": "https://www.sorbillo.it/",
  "facebook": "https://www.facebook.com/PizzeriaGinoSorbillo/",
  "instagram": "https://www.instagram.com/sorbillo/",
  "hours": "8:30-10:30;12:30-15:30",
  "description": "Gino Sorbillo appartiene ad una delle famiglie di pizzaioli più antiche di Napoli. cresce nella pizzeria di famiglia e ben presto impara i segreti della vera pizza napoletana. Con Gino Sorbillo la Pizza Napoletana è giunta a livelli qualitativi altissimi e si è guadagnata di diritto spazio tra le migliori eccellenze gastronomiche italiane.",
  "dishes": [
    {
      "name": "Pasta Carbonara",
      "price": 10.99,
      "type": "pasta",
      "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAEnQAABJ0Ad5mH3gAAABrSURBVBhXHcaxCoJQFIDh39MVLBpCtLmtoAafNHqThp7HwUUEE0yKuB6vp3D44Iuut9KK/Z1L/iBNKiRSZGUB+WOGEBw6rRGCLHn7jO5zoBnOuFG3tMMJUwcGX5/i/Lij7gueryM2x0y64Qemmyv/QTYLjwAAAABJRU5ErkJggg==",
      "ingredients": [
        {
         "name": "Spaghetti",
         "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAEnQAABJ0Ad5mH3gAAABrSURBVBhXHcaxCoJQFIDh39MVLBpCtLmtoAafNHqThp7HwUUEE0yKuB6vp3D44Iuut9KK/Z1L/iBNKiRSZGUB+WOGEBw6rRGCLHn7jO5zoBnOuFG3tMMJUwcGX5/i/Lij7gueryM2x0y64Qemmyv/QTYLjwAAAABJRU5ErkJggg==",
         "allergens":"bfbb",
         "brandName":"ngerj",
         "brandLink":"vmero"
        },
        {
         "name": "Bacon",
         "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAEnQAABJ0Ad5mH3gAAABrSURBVBhXHcaxCoJQFIDh39MVLBpCtLmtoAafNHqThp7HwUUEE0yKuB6vp3D44Iuut9KK/Z1L/iBNKiRSZGUB+WOGEBw6rRGCLHn7jO5zoBnOuFG3tMMJUwcGX5/i/Lij7gueryM2x0y64Qemmyv/QTYLjwAAAABJRU5ErkJggg==",
         "allergens":"bfbb",
         "brandName":"ngerj",
         "brandLink":"vmero"
        }
      ]
    },
    {
      "name": "Margherita Pizza",
      "price": 12.99,
      "type": "pizza",
      "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAEnQAABJ0Ad5mH3gAAABrSURBVBhXHcaxCoJQFIDh39MVLBpCtLmtoAafNHqThp7HwUUEE0yKuB6vp3D44Iuut9KK/Z1L/iBNKiRSZGUB+WOGEBw6rRGCLHn7jO5zoBnOuFG3tMMJUwcGX5/i/Lij7gueryM2x0y64Qemmyv/QTYLjwAAAABJRU5ErkJggg==",
      "ingredients": [
        {
         "name": "Tomato Sauce",
         "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAEnQAABJ0Ad5mH3gAAABrSURBVBhXHcaxCoJQFIDh39MVLBpCtLmtoAafNHqThp7HwUUEE0yKuB6vp3D44Iuut9KK/Z1L/iBNKiRSZGUB+WOGEBw6rRGCLHn7jO5zoBnOuFG3tMMJUwcGX5/i/Lij7gueryM2x0y64Qemmyv/QTYLjwAAAABJRU5ErkJggg==",
         "allergens":"bfbb",
         "brandName":"ngerj",
         "brandLink":"vmero"
        },
        {
         "name": "Mozzarella Cheese",
         "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAEnQAABJ0Ad5mH3gAAABrSURBVBhXHcaxCoJQFIDh39MVLBpCtLmtoAafNHqThp7HwUUEE0yKuB6vp3D44Iuut9KK/Z1L/iBNKiRSZGUB+WOGEBw6rRGCLHn7jO5zoBnOuFG3tMMJUwcGX5/i/Lij7gueryM2x0y64Qemmyv/QTYLjwAAAABJRU5ErkJggg==",
         "allergens":"bfbb",
         "brandName":"ngerj",
         "brandLink":"vmero"
        }
      ]
    }
  ]
}

###

## Update a Restaurant Given his ID
POST http://localhost:3001/api/restaurants/7 HTTP/1.1
content-type: application/json

{
  "id": 7,
  "isNewInserted": 0,
  "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAEnQAABJ0Ad5mH3gAAABrSURBVBhXHcaxCoJQFIDh39MVLBpCtLmtoAafNHqThp7HwUUEE0yKuB6vp3D44Iuut9KK/Z1L/iBNKiRSZGUB+WOGEBw6rRGCLHn7jO5zoBnOuFG3tMMJUwcGX5/i/Lij7gueryM2x0y64Qemmyv/QTYLjwAAAABJRU5ErkJggg==",
  "name": "Sorbillo",
  "location": "Via Bruno Buozzi, 3, 10121 Torino TO",
  "phone": "011 1923 4672",
  "website": "https://www.sorbillo.it/",
  "facebook": "https://www.facebook.com/PizzeriaGinoSorbillo/",
  "instagram": "https://www.instagram.com/sorbillo/",
  "hours": "8:30-10:30;12:30-15:30",
  "description": "Gino Sorbillo appartiene ad una delle famiglie di pizzaioli più antiche di Napoli. cresce nella pizzeria di famiglia e ben presto impara i segreti della vera pizza napoletana. Con Gino Sorbillo la Pizza Napoletana è giunta a livelli qualitativi altissimi e si è guadagnata di diritto spazio tra le migliori eccellenze gastronomiche italiane.",
  "dishes": [
    {
      "id": 7,
      "name": "Pasta Carbonara",
      "price": 10.99,
      "type": "pasta",
      "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAEnQAABJ0Ad5mH3gAAABrSURBVBhXHcaxCoJQFIDh39MVLBpCtLmtoAafNHqThp7HwUUEE0yKuB6vp3D44Iuut9KK/Z1L/iBNKiRSZGUB+WOGEBw6rRGCLHn7jO5zoBnOuFG3tMMJUwcGX5/i/Lij7gueryM2x0y64Qemmyv/QTYLjwAAAABJRU5ErkJggg==",
      "ingredients": [
        {
         "id": 7,
         "name": "Spaghetti",
         "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAEnQAABJ0Ad5mH3gAAABrSURBVBhXHcaxCoJQFIDh39MVLBpCtLmtoAafNHqThp7HwUUEE0yKuB6vp3D44Iuut9KK/Z1L/iBNKiRSZGUB+WOGEBw6rRGCLHn7jO5zoBnOuFG3tMMJUwcGX5/i/Lij7gueryM2x0y64Qemmyv/QTYLjwAAAABJRU5ErkJggg==",
         "allergens":"bfbb",
         "brandName":"ngerj",
         "brandLink":"vmero"
        },
        {
         "id": 8,
         "name": "Bacon",
         "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAEnQAABJ0Ad5mH3gAAABrSURBVBhXHcaxCoJQFIDh39MVLBpCtLmtoAafNHqThp7HwUUEE0yKuB6vp3D44Iuut9KK/Z1L/iBNKiRSZGUB+WOGEBw6rRGCLHn7jO5zoBnOuFG3tMMJUwcGX5/i/Lij7gueryM2x0y64Qemmyv/QTYLjwAAAABJRU5ErkJggg==",
         "allergens":"bfbb",
         "brandName":"ngerj",
         "brandLink":"vmero"
        }
      ]
    },
    {
      "id": 8,
      "name": "Margherita Pizza",
      "price": 12.99,
      "type": "pizza",
      "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAEnQAABJ0Ad5mH3gAAABrSURBVBhXHcaxCoJQFIDh39MVLBpCtLmtoAafNHqThp7HwUUEE0yKuB6vp3D44Iuut9KK/Z1L/iBNKiRSZGUB+WOGEBw6rRGCLHn7jO5zoBnOuFG3tMMJUwcGX5/i/Lij7gueryM2x0y64Qemmyv/QTYLjwAAAABJRU5ErkJggg==",
      "ingredients": [
        {
         "id" : 9,
         "name": "Tomato Sauce",
         "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAEnQAABJ0Ad5mH3gAAABrSURBVBhXHcaxCoJQFIDh39MVLBpCtLmtoAafNHqThp7HwUUEE0yKuB6vp3D44Iuut9KK/Z1L/iBNKiRSZGUB+WOGEBw6rRGCLHn7jO5zoBnOuFG3tMMJUwcGX5/i/Lij7gueryM2x0y64Qemmyv/QTYLjwAAAABJRU5ErkJggg==",
         "allergens":"bfbb",
         "brandName":"ngerj",
         "brandLink":"vmero"
        },
        {
         "id": 10,
         "name": "Mozzarella Cheese",
         "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAEnQAABJ0Ad5mH3gAAABrSURBVBhXHcaxCoJQFIDh39MVLBpCtLmtoAafNHqThp7HwUUEE0yKuB6vp3D44Iuut9KK/Z1L/iBNKiRSZGUB+WOGEBw6rRGCLHn7jO5zoBnOuFG3tMMJUwcGX5/i/Lij7gueryM2x0y64Qemmyv/QTYLjwAAAABJRU5ErkJggg==",
         "allergens":"bfbb",
         "brandName":"ngerj",
         "brandLink":"vmero"
        }
      ]
    }
  ]
}

###

# Delete the restaurant.
DELETE http://localhost:3001/api/restaurants/2 HTTP/1.1
###

## Get a review from his id.
GET http://localhost:3001/api/reviews/1 HTTP/1.1
###

## Insert a new review
POST http://localhost:3001/api/reviews/ HTTP/1.1
content-type: application/json

{
  "username": "User",
  "restaurantId": "1",
  "date": "2023-02-28",
  "title": "Great Experience",
  "description": "Had a wonderful time!",
  "quality": "4.5",
  "safety": "4.0",
  "price": "4.0"
}
###

## Update a review Given his ID
POST http://localhost:3001/api/reviews/6 HTTP/1.1
content-type: application/json

{
  "id" : "11",
  "username": "Giuseppe",
  "restaurantId": "1",
  "date": "2024-03-4",
  "title": "Great ",
  "description": "wonderful!",
  "quality": "1",
  "safety": "5",
  "price": "1"
}
###

# Delete the review Given his ID
DELETE http://localhost:3001/api/reviews/8 HTTP/1.1
###

## Get all reviews of a user from his username
GET http://localhost:3001/api/reviews/users/Andrea HTTP/1.1
###